[ROCm] add ROCm support (pt. 2) (#7039)
* [ROCm] re-add support for ROCm builds

Previously #6086 added ROCm support but after numerous rebases it lost
critical changes. This PR restores the ROCm build.

There are many source file changes but most were automated using the
following:

```bash
for f in `grep -rl '#ifdef USE_CUDA'`
do
    sed -i 's@#ifdef USE_CUDA@#if defined(USE_CUDA) || defined(USE_ROCM)@g' $f
done

for f in `grep -rl '#endif  // USE_CUDA'`
do
    sed -i 's@#endif  // USE_CUDA@#endif  // USE_CUDA || USE_ROCM@g' $f
done
```

* Fix error in cpp_tests/test_arrow.cpp.

error: explicit specialization in non-namespace scope ‘class ArrowChunkedArrayTest’

* update for ROCm 7 BC-breaking change to warpSize

* lint

* Revert "Fix error in cpp_tests/test_arrow.cpp."

This reverts commit e461e868de85a6b7ef8aceeaaf95cf39d7420ab3.

* partial revert of 61ec4f1aa215ca3381e7b79e98f002dc0c021d77

Instead of replacing all #ifdef USE_CUDA, just add USE_CUDA define to ROCm build.

* add --use-rocm option to build-python.sh

* fix cuda build missing CUDASUCCESS_OR_FATAL in vector_cudahost.h

* add rocm docs

* fix doc using pre-commit

* apply reviewer suggestions

* fix build-python.sh doc

* fix build for rocm 7.0

---------

Co-authored-by: James Lamb <jaylamb20@gmail.com>
Co-authored-by: shiyu1994 <shiyu_k1994@qq.com>
Co-authored-by: Nikita Titov <nekit94-08@mail.ru>